-- liquibase formatted sql

-- changeset MubarekMohammed:1755717874039-1
CREATE TABLE resource_owner
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    username   VARCHAR(255),
    password   VARCHAR(255),
    role       VARCHAR(255),
    birth_date date,
    CONSTRAINT pk_resourceowner PRIMARY KEY (id)
);

